# render.yaml - Configuración específica para Honk Kong en Render.com
services:
  - type: web
    name: honk-kong-web
    runtime: php
    phpVersion: 8.2
    buildCommand: bash build.sh  # Esto es suficiente si tienes el archivo build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true

      # Configuración PostgreSQL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1o1586r433s738bi9fg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: hong-kong
      - key: DB_USERNAME
        value: hong_kong_user
      - key: DB_PASSWORD
        value: Pa78c48Qm3OM6WmVj1s1kwez5GmFvUJ9

      # Otras variables (ejemplo: configuración de mail o APIs externas)
      # - key: MAIL_MAILER
      #   value: smtp
      # - key: MAIL_HOST
      #   value: sandbox.smtp.mailtrap.io
      # ... añade aquí otras variables necesarias desde tu .env local

# Si necesitas un worker para colas (opcional):
# - type: worker
#   name: honk-kong-worker
#   startCommand: php artisan queue:work --tries=3
#   envVars:
#     - key: APP_ENV
#       value: production
