# render.yaml - Configuración específica para Honk Kong en Render.com
services:
  - type: web
    name: honk-kong-web  # Nombre del servicio web en Render
    runtime: php   
     phpVersion: 8.2 
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan optimize:clear
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    envVars:
      # Configuración básica de Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true  # Render generará automáticamente una clave

      # Configuración de PostgreSQL (datos específicos de tu DB en Render)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1o1586r433s738bi9fg-a  # Hostname proporcionado por Render
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: hong-kong  # Nombre de la base de datos
      - key: DB_USERNAME
        value: hong_kong_user  # Usuario de la DB
      - key: DB_PASSWORD
        value: Pa78c48Qm3OM6WmVj1s1kwez5GmFvUJ9  # Contraseña de la DB

      # Otras variables (ejemplo: configuración de mail o APIs externas)
      # - key: MAIL_MAILER
      #   value: smtp
      # - key: MAIL_HOST
      #   value: sandbox.smtp.mailtrap.io
      # ... añade aquí otras variables necesarias desde tu .env local

# Si necesitas un worker para colas (opcional):
# - type: worker
#   name: honk-kong-worker
#   startCommand: php artisan queue:work --tries=3
#   envVars:
#     - key: APP_ENV
#       value: production
